FanBucketUI/Pages/Admin/Users.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using FanBucketEntity.Wrappers;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.Admin
{
    public class UsersModel : PageModel
    {
        public PagedResponse<List<UserDetailsViewModel>> pagedUsrlist = new PagedResponse<List<UserDetailsViewModel>>();
        bool response = false;
        [BindProperty]
        public string UserId { get; set; }

        private readonly apiRequest api;
        public UsersModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }
        public async Task<IActionResult> OnGet(string msg, int PageNumber = 1, int PageSize = 10, string searchText = "")
        {

            pagedUsrlist = await api.GetUsers(User.Identity.GetJWT(), PageNumber, PageSize,searchText);
            return Page();
        }
        public async Task<IActionResult> OnPostVerify()
        {

            var user = User.Identity.GetUserId();
            response = await api.VerifyUserById(UserId, User.Identity.GetJWT());
            return RedirectToPage("Users");
        }

        public async Task<IActionResult> OnGetPartial(string msg, int PageNumber = 1, int PageSize = 10, string searchText = "")
        {

           var pagedList1 = await api.GetUsers(User.Identity.GetJWT(), PageNumber, PageSize, searchText);
            return Partial("_UserList",pagedList1);
        }
    }
}

FanBucketUI/Pages/User/Details.cshtml.cs
using FanBucketAPI.Helper;
using FanBucketAPI.ViewModel;
using FanBucketEntity.Model.ENUM;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FanBucketUI.Pages.User
{
    public class DetailsModel : PageModel
    {
        public UserDetailsViewModel usr = new UserDetailsViewModel();
        [BindProperty]
        public ReportActionViewModel ReportActionViewModel { get; set; }
        [BindProperty]
        public CommissionReviewViewModel CommissionReviewViewModel { get; set; }

        private readonly apiRequest api;

        public List<SelectListItem> Actions { get; set; }
        public List<SelectListItem> Days { get; set; }


        public DetailsModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }
        private void Common()
        {
            Actions = EnumHelper.GetEnumValuesAndDescriptions<EnumReportAction>().ToList();
            Days = EnumHelper.GetEnumValuesAndDescriptions<EnumDays>().ToList();
        }
        public async Task<IActionResult> OnGet(Guid Id)
        {
            usr = await api.GetUserDetailsById(Id, User.Identity.GetJWT()); 
            Common();
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await api.UserCommissionReview(CommissionReviewViewModel, User.Identity.GetJWT());
            Common();
            return RedirectToPage("./Details", new { Id = CommissionReviewViewModel.UserId });
        }

        public async Task<IActionResult> OnPostUserReview()
        {
            var user = User.Identity.GetUserId();
            await api.UserReview(ReportActionViewModel, User.Identity.GetJWT());
            return RedirectToPage("./Details", new { Id = ReportActionViewModel.UserId });
        }
    }
}

FanBucketUI/Pages/User/EditProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.User
{
    public class EditProfileModel : PageModel
    {
        public UserDetailsViewModel usr = new UserDetailsViewModel();

        private readonly apiRequest api;
        public EditProfileModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }
        public async Task<IActionResult> OnGet(Guid Id)
        {


            usr = await api.GetUserDetail(User.Identity.GetJWT());
            return Page();
        }

        public async Task<IActionResult> OnPost(EditPersonalViewModel model)
        {


            usr = await api.GetUserDetail(User.Identity.GetJWT());
            return Page();
        }
    }
}

FanBucketUI/Pages/User/ForgotPassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.User
{
    public class ForgotPasswordModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

FanBucketUI/Pages/User/GuestUserPostByImageContent.cshtml.cs
using FanBucketAPI.Models;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace FanBucketUI.Pages.Post
{
    public class GuestUserPostByImageContentModel : PageModel
    {
        //public List<PostMasterCollectionViewModel> postMaster = new List<PostMasterCollectionViewModel>();
        public List<GetUserMediaViewModel> userMedias = new List<GetUserMediaViewModel>();
        private readonly apiRequest api;

        public GuestUserPostByImageContentModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }

        public async Task<IActionResult> OnGet()
        {
            userMedias = await api.GetPostByImageAsGuestUser(User.Identity.GetJWT());

            return Page();
        }
    }
}

FanBucketUI/Pages/User/GuestUserPostByVideoContent.cshtml.cs
using FanBucketAPI.Models;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace FanBucketUI.Pages.Post
{
    public class GuestUserPostByVideoContentModel : PageModel
    {
        public List<PostMasterCollectionViewModel> postMaster = new List<PostMasterCollectionViewModel>();
        private readonly apiRequest api;

        public GuestUserPostByVideoContentModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }

        public async Task<IActionResult> OnGet()
        {
            postMaster = await api.GetUserPostByVideoAsGuestUser(User.Identity.GetJWT());

            return Page();
        }
    }
}

FanBucketUI/Pages/User/LoadWallet.cshtml.cs
using FanBucketAPI.Helper;
using FanBucketAPI.ViewModel;
using FanBucketEntity.Model.ENUM;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FanBucketUI.Pages.User
{
    public class LoadWalletModel : PageModel
    {

        [BindProperty(SupportsGet = true)]
        public decimal amount { get; set; }


        public LoadWalletModel()
        {
            amount = 0;
        }

        public async Task<IActionResult> OnGet(decimal Amount)
        {
            if (amount<=0)
            {
                return RedirectToPage("/Post/Feed");
            }
            amount = Amount;

            return Page();
        }


    }
}

FanBucketUI/Pages/User/Notifications.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.User
{
    public class NotificationsModel : PageModel
    {
        public List<NotificationViewModel> postMaster = new List<NotificationViewModel>();
        private readonly apiRequest api;
        public NotificationsModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }
        public async Task<IActionResult> OnGet()
        {

            postMaster = await api.GetUserNotifications(User.Identity.GetJWT());
            return Page();
        }
    }
}

FanBucketUI/Pages/User/PaymentHistory.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.Procedure;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.User
{
    [Authorize]
    public class PaymentHistoryModel : PageModel
    {
        public List<PaymentHistory> postMaster = new List<PaymentHistory>();
        private readonly apiRequest api;
        public PaymentHistoryModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }
        public async Task<IActionResult> OnGet(Guid NotifyId=default)
        {

            postMaster = await api.GetPaymentHistory(NotifyId,User.Identity.GetJWT());
            return Page();
        }
    }
}

FanBucketUI/Pages/User/PostImages.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.Post
{
    [Authorize]
    public class PostImagesModel : PageModel
    {
        //public List<PostMasterCollectionViewModel> postMaster = new List<PostMasterCollectionViewModel>();
        //public List<GetUserImageContents> postMaster = new List<GetUserImageContents>();
        private readonly apiRequest api;
        public List<GetUserMediaViewModel> userMedias=new List<GetUserMediaViewModel>();

        public PostImagesModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }


        public async Task<IActionResult> OnGet(Guid Id)
        {


            userMedias = await api.GetUserImageContents(Id, User.Identity.GetJWT());

            return Page();
        }
    }
}

FanBucketUI/Pages/User/PostVideo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketAPI.Models;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.Post
{
    public class PostVideoModel : PageModel
    {
        public List<PostMasterCollectionViewModel> postMaster = new List<PostMasterCollectionViewModel>();
        private readonly apiRequest api;
        public PostVideoModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }

        public async Task<IActionResult> OnGet(Guid Id)
        {

            

            postMaster = await api.GetVideos(Id, User.Identity.GetJWT());

            return Page();
        }

    }
}

FanBucketUI/Pages/User/ProfilePage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;

namespace FanBucketUI.Pages.User
{
    public class ProfilePageModel : PageModel
    {
        public UserDetailsViewModel usr = new UserDetailsViewModel();

        private readonly apiRequest api;
        public ProfilePageModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }

        public async Task<IActionResult> OnGet(string Username,string NotifyId=null)
        {
            if (User.Identity.IsAuthenticated)
            {
                usr = await api.GetUsersById(Username, User.Identity.GetJWT(),NotifyId);
                return Page();
            }
            else
            {
                return Redirect("/U/" + Username);
            }

        }

        //public async Task<IActionResult> OnGetUpdateFeaturedBadge(string BadgeCode)
        //{
        //    var api = new apiRequest();
        //    var flag= await api.UpdateFeaturedBadge(BadgeCode, User.Identity.GetJWT());
        //    if (flag)
        //    {
        //      return  RedirectToPage("/ProfilePage",new { Id=User.Identity.GetUserId()});
        //    }
        //    else
        //    {

        //    }
        //    return Page();
        //}



    }
}

FanBucketUI/Pages/User/RecommendedUser.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.User
{
    public class RecommendedUserModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

FanBucketUI/Pages/User/ResetPassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.User
{
    public class ResetPasswordModel : PageModel
    {
        public ResetPasswordViewModel resetToken = new ResetPasswordViewModel();
        public async Task<IActionResult> OnGet(string token, string email)
        {
            if (token == null || email == null)
            {
                return BadRequest("Invalid Token");
            }
            resetToken.Token = token;
            resetToken.Email = email;
            return Page();
        }

    }
}

FanBucketUI/Pages/User/ScheduledPost.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketAPI.Models;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.User
{
    public class ScheduledPostModel : PageModel
    {
        public List<PostMasterCollectionViewModel> postMaster = new List<PostMasterCollectionViewModel>();
        private readonly apiRequest api;
        public ScheduledPostModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }
        public DateTime ClientsTime;

        public async Task<IActionResult> OnGet(DateTime dateTime)
        {
            ClientsTime = dateTime;
            postMaster = await api.GetScheduled(User.Identity.GetJWT());

            return Page();
        }
    }
}

FanBucketUI/Pages/User/Settings.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json.Linq;

namespace FanBucketUI.Pages.User
{
    public class SettingsModel : PageModel
    {
        private readonly apiRequest _apirequest;

        public  SettingsViewModel SettingsViewModel { get; set; }
        public SettingsModel(apiRequest  apirequest)
        {
            _apirequest = apirequest;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            SettingsViewModel = await _apirequest.GetSettings(User.Identity.GetJWT());
            return Page();
            //var claimNew = new Claim(type, value);
            //var claimOld = new Claim(type, oldValue);
            //var result = await UserManager.ReplaceClaimAsync(user, claimOld, claimNew);
        }
    }
}

FanBucketUI/Pages/User/UserAnalytics.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.User
{
    [Authorize]
    public class UserAnalyticsModel : PageModel
    {
        public UserInteractionViewModel usrInt = new UserInteractionViewModel();


        private readonly apiRequest api;
        public UserAnalyticsModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }
        public async Task<ActionResult> OnGet()
        {
            usrInt = await api.GetUserData(User.Identity.GetJWT());

            return Page();
        }
    }
}

FanBucketUI/Pages/User/UserBySearch.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.User
{
    public class UserBySearchModel : PageModel
    {
        public List<SearchUserViewModel> usrlist = new List<SearchUserViewModel>();
        private readonly apiRequest api;
        public UserBySearchModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }
        public async Task<IActionResult> OnGet(string msg)
        {

            usrlist = await api.GetUsersBySearch(msg, User.Identity.GetJWT());
            return Page();
        }

    }
}

FanBucketUI/Pages/User/Details.cshtml
@page
@model FanBucketUI.Pages.User.DetailsModel
@{
    Layout = "../Shared/_LayoutAdmin.cshtml";
}

<main class="insights--aside dashboard--main">
    <div class="right--aside__wrapper chat--wrapper">
        <section class="dashboard__general">
            <h2 class="section__title">User Info</h2>
            <div class="">

                <div href="#" class="mb-3" aria-current="true">
                    <div class="profile--card">
                        <div class="card__img active">
                            <img src="@Model.usr.ProfileImgLocation" alt="">
                        </div>
                        <div class="card__body">
                            <h2 class="card__title">Username: @Model.usr.Username</h2>
                            <div class="para-wrapper">
                                <p class="para small">Fullname: @Model.usr.Fullname</p>
                                <p class="para small">Email: @Model.usr.Email</p>
                                <p class="para small">Status: @Model.usr.Status</p>
                                @if (Model.usr.BlockTill.HasValue)
                                {
                                    <p class="para small">Block Till: @Model.usr.BlockTill.Value.ToLongDateString()</p>

                                }
                                @*<p class="para small">AccountType: @Html.DisplayFor(x => Model.usr.AccountType)</p>*@
                                @{
                                    var KYC = Model.usr.KYC_Details;
                                    var BalanceInfo = Model.usr.BalanceInfo;
                                }
                                @if (KYC != null)
                                {
                                    <p class="para small">Gender: @KYC.Gender</p>
                                    <p class="para small">DOB: @KYC.DOB</p>
                                    <p class="para small">Identification: @KYC.Identification</p>
                                    <p class="para small">Id No: @KYC.IdNO</p>
                                    <p class="para small">Id Issued From: @KYC.IdIssuedFrom</p>
                                    <p class="para small">Contact Number: @KYC.ContactNumber</p>
                                    <p class="para small">Expiry: @KYC.Expiry</p>
                                }
                                @if (BalanceInfo != null)
                                {
                                    <p class="para small">Currency: @BalanceInfo.Currency</p>
                                    @*<p class="para small">Credit Sum: @BalanceInfo.CreditSum</p>
                                        <p class="para small">Debit Sum: @BalanceInfo.DebitSum</p>*@
                                    <p class="para small">Current Balance: @Math.Round(BalanceInfo.CurrentBalance,2)</p>
                                    <p class="para small">Earning %: @Math.Round(BalanceInfo.EarningPercentage,2)</p>

                                }
                            </div>

                        </div>
                    </div>
                </div>

            </div>
            <ul class="nav nav-tabs">
                <li class="nav-item"><a data-toggle="tab" href="#user_review" class="active nav-link">User Review</a></li>

                <li class="nav-item"><a data-toggle="tab" href="#commission_review" class=" nav-link">Commission Review</a></li>
            </ul>

            <div class="tab-content">
                <div id="commission_review" class="tab-pane fade">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title  text-body">User Commission Review</div>
                        </div>

                        <form method="post" class="card-body" enctype="multipart/form-data">
                            <input type="hidden" asp-for="CommissionReviewViewModel.UserId" value="@Model.usr.Id" />
                            <div class="col-sm-6 col-md-6">
                                <div class="form-group">
                                    <label asp-for="CommissionReviewViewModel.NewCommissionPer" class="control-label">New Commission %</label>
                                    <input asp-for="CommissionReviewViewModel.NewCommissionPer" type="number" class="form-control" />
                                    <span asp-validation-for="CommissionReviewViewModel.NewCommissionPer" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-12">
                                <div class="form-group">
                                    <label asp-for="CommissionReviewViewModel.Remarks" class="control-label"></label>
                                    <textarea asp-for="CommissionReviewViewModel.Remarks" class="form-control"></textarea>
                                    <span asp-validation-for="CommissionReviewViewModel.Remarks" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-4">
                                <div class="form-group">
                                    <button class="btn btn-success" type="submit">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
                <div id="user_review" class="tab-pane fade in active show">
                    @{
                        var act = Model.usr.ActiveReports;
                    }
                    <section class="dashboard__general">

                        @if (act != null)
                        {

                            <div class="card pb-0">
                                <div class="card-header ">
                                    Reports
                                </div>
                                <div class="card-body">
                                    @{

                                        int i = 1;
                                    }
                                    <div class="">
                                        Last Reported Date: @Html.DisplayFor(x => act.LastReportedDate)
                                        <br />
                                        No of Active Reports: @Html.DisplayFor(x => act.NoOfReports)
                                    </div>
                                    <div class="table-responsive">
                                        <table class="table table-striped" style="width:100%">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Reported Date</th>
                                                    <th>Reason</th>
                                                    <th>Remarks</th>
                                                    <th>Reported By </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in act.Reports)
                                                {

                                                    <tr>
                                                        <td>@i</td>
                                                        <td>@item.CreatedOn</td>
                                                        <td>
                                                            @item.ReportingReason
                                                        </td>
                                                        <td>@item.Remarks</td>
                                                        <td>@item.ReportedbyFullname</td>
                                                    </tr>


                                                    i++;
                                                }
                                            </tbody>
                                        </table>
                                    </div>

                                </div>

                            </div>


                        }
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title text-body">User Review</div>
                            </div>

                            <form method="post" asp-page-handler="UserReview" class="card-body" enctype="multipart/form-data">
                                <input type="hidden" asp-for="ReportActionViewModel.UserId" value="@Model.usr.Id" />
                                <div class="col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <label asp-for="ReportActionViewModel.Action" class="control-label"></label>
                                        <select asp-for="ReportActionViewModel.Action" class="form-control" asp-items="Model.Actions">
                                            <option value="">Select an Option</option>
                                        </select>
                                        <span asp-validation-for="ReportActionViewModel.Action" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-sm-6 col-md-6" id="block_options">
                                    <div class="form-group">
                                        <label asp-for="ReportActionViewModel.BlockDays" class="control-label"></label>
                                        <select asp-for="ReportActionViewModel.BlockDays" class="form-control" asp-items="Model.Days">
                                            <option value="">Select an Option</option>
                                        </select>
                                        <span asp-validation-for="ReportActionViewModel.BlockDays" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label asp-for="ReportActionViewModel.Remarks" class="control-label"></label>
                                        <textarea asp-for="ReportActionViewModel.Remarks" class="form-control"></textarea>
                                        <span asp-validation-for="ReportActionViewModel.Remarks" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-sm-6 col-md-4">
                                    <div class="form-group">
                                        <button class="btn btn-success" type="submit">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>

                    </section>
                </div>

            </div>
        </section>
    </div>

</main>
@section Scripts{
    <script>
        $(document).ready(function () {
            $("#ReportActionViewModel_Action").change(function () {
                var currentVal = $(this).val();
                console.log(currentVal);
                if (currentVal === "") {
                    return;
                }
                if (currentVal === '1') {
                    $('#block_options').addClass("d-none");
                } else {
                    $('#block_options').removeClass("d-none");

                }
            });
        });
    </script>
}

FanBucketUI/Pages/User/GuestUserPostByImageContent.cshtml
@page
@model FanBucketUI.Pages.Post.GuestUserPostByImageContentModel
@{
    Layout = null;
}

@*@inject FanBucketUI.API_Context.SessionHelper uservice
@{
    var Username = uservice.GetUsername(User);
    var userFullname = uservice.GetName(User);
    var userImg = uservice.GetProfileImg(User);
    var userId = Guid.Parse(uservice.GetId(User));
}*@
<partial name="_ImageGrid" for="userMedias" />
<script>
      // A $( document ).ready() block.
    $( document ).ready(function() {
    Fancybox.destroy("[data-fancybox]");
                            Fancybox.bind("[data-fancybox]", {
                                // Your options go here
                            });
    });

</script>

FanBucketUI/Pages/User/LoadWallet.cshtml
@page "{Amount}"
@model FanBucketUI.Pages.User.LoadWalletModel
@{
    Layout = null;
    //Layout = "../Shared/_LayoutAdmin.cshtml";
}
@inject FanBucketUI.API_Context.SessionHelper uservice;
@{
    var hash___ = uservice.GetBearer(User);

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Accept a payment</title>
    <meta name="description" content="A demo of a payment on Stripe" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="@Url.Content("/LoadWallet.css")" />
    <script src="https://js.stripe.com/v3/"></script>
</head>
<body>
    <input id="token___Auth" value="@hash___" hidden />
    <input id="username" value="@(User.Identity.GetUsername())" hidden />
    @*<label>
          <span>Name</span>
          <input name="name" class="field" placeholder="Jenny Rosen" required>
        </label>*@
    <!-- Display a payment form -->
    <form id="payment-form">
        <div id="payment-element">

            <!--Stripe.js injects the Payment Element-->
        </div>
        <button id="submit">
            <div class="spinner hidden" id="spinner"></div>
            <span id="button-text">Pay now</span>
        </button>
        <div id="payment-message" class="hidden"></div>
    </form>
</body>
</html>
<script>
    var amount =@(Model.amount);

</script>
@{await Html.RenderPartialAsync("Config");}

<script src="@Url.Content("/LoadWallet.js")" defer></script>