FanBucketUI/Pages/Admin/Dashboard.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.Admin
{

    public class DashboardModel : PageModel
    {
        public DashboardViewModel dashboardViewModel = new DashboardViewModel();
        private readonly apiRequest api;
        public DashboardModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }


        public async Task<IActionResult> OnGet()
        {
           
            dashboardViewModel = await api.GetDashboardInfo(User.Identity.GetJWT(), 7);
            return Page();
        }
    }
}

FanBucketUI/Pages/Admin/NewUsers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.Admin
{
    public class NewUsersModel : PageModel
    {
        public List<UserDetailsViewModel> newUsrlist = new List<UserDetailsViewModel>();
        private readonly apiRequest api;
        public NewUsersModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }

        public async Task<IActionResult> OnGet(string msg)
        {

            newUsrlist = await api.GetNewUsers(User.Identity.GetJWT(), 7);
            return Page();
        }
    }
}

FanBucketUI/Pages/Admin/PostReportedDetails.cshtml.cs
using FanBucketAPI.Helper;
using FanBucketAPI.ViewModel;
using FanBucketEntity.Model.ENUM;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FanBucketUI.Pages.Admin
{
    public class PostReportedDetailsModel : PageModel
    {
        public PostReportSummaryViewModel reportedPost = new PostReportSummaryViewModel();
        private readonly apiRequest api;

        [BindProperty]
        public PostReviewViewModel PostReviewViewModel { get; set; }

        [ViewData]
        public List<SelectListItem> NewStatus { get; set; }

        private void Common()
        {
            NewStatus = EnumHelper.GetEnumValuesAndDescriptions<Record_Status>().ToList();
        }

        public PostReportedDetailsModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }

        public async Task<IActionResult> OnGet(Guid Id)
        {
            reportedPost = await api.ReportedPostsDetails(Id, User.Identity.GetJWT());
            Common();
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            var user = User.Identity.GetUserId();
            await api.PostReview(PostReviewViewModel, User.Identity.GetJWT());
            return RedirectToPage("./PostsReported");
        }
    }
}

FanBucketUI/Pages/Admin/ReportedPosts.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketAPI.APIModels;
using FanBucketAPI.ViewModel;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.Admin
{
    
    public class ReportedPostsModel : PageModel
    {
        public List<PostReportSummaryViewModel> reportedPostList = new List<PostReportSummaryViewModel>();
        private readonly apiRequest api;
        public ReportedPostsModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }

        public async Task<IActionResult> OnGet()
        {
            reportedPostList = await api.ReportedPosts(User.Identity.GetJWT());
            return Page();
        }
       
    }
}

FanBucketUI/Pages/Admin/ReportedUsers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketAPI.APIModels;
using FanBucketAPI.ViewModel;
using FanBucketEntity.ViewModel;
using FanBucketRepo.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.Admin
{

    public class ReportedUsersModel : PageModel
    {
        public List<UserReportSummaryViewModel> reportedPostList = new List<UserReportSummaryViewModel>();
        private readonly apiRequest api;
        public ReportedUsersModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }

        public async Task<IActionResult> OnGet()
        {
            reportedPostList = await api.ReportedUsers(User.Identity.GetJWT());
            return Page();
        }
       
    }
}

FanBucketUI/Pages/Admin/UserReportedDetails.cshtml.cs
using FanBucketAPI.Helper;
using FanBucketAPI.ViewModel;
using FanBucketEntity.Model.ENUM;
using FanBucketRepo.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FanBucketUI.Pages.Admin
{
    public class UserReportedDetailsModel : PageModel
    {
        public UserReportSummaryViewModel reportedUser = new UserReportSummaryViewModel();
        private readonly apiRequest api;

        [BindProperty]
        public ReportActionViewModel ReportActionViewModel { get; set; }

        public List<SelectListItem> Actions { get; set; }
        public List<SelectListItem> Days { get; set; }

        private void Common()
        {
            Actions = EnumHelper.GetEnumValuesAndDescriptions<EnumReportAction>().ToList();
            Days = EnumHelper.GetEnumValuesAndDescriptions<EnumDays>().ToList();
        }

        public UserReportedDetailsModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }

        public async Task<IActionResult> OnGet(Guid Id)
        {
            reportedUser = await api.ReportedUserDetails(Id, User.Identity.GetJWT());
            Common();
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            var user = User.Identity.GetUserId();
            await api.UserReview(ReportActionViewModel, User.Identity.GetJWT());
            return RedirectToPage("./UsersReported");
        }
    }
}

FanBucketUI/Pages/Admin/Users.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using FanBucketEntity.Wrappers;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.Admin
{
    public class UsersModel : PageModel
    {
        public PagedResponse<List<UserDetailsViewModel>> pagedUsrlist = new PagedResponse<List<UserDetailsViewModel>>();
        bool response = false;
        [BindProperty]
        public string UserId { get; set; }

        private readonly apiRequest api;
        public UsersModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }
        public async Task<IActionResult> OnGet(string msg, int PageNumber = 1, int PageSize = 10, string searchText = "")
        {

            pagedUsrlist = await api.GetUsers(User.Identity.GetJWT(), PageNumber, PageSize,searchText);
            return Page();
        }
        public async Task<IActionResult> OnPostVerify()
        {

            var user = User.Identity.GetUserId();
            response = await api.VerifyUserById(UserId, User.Identity.GetJWT());
            return RedirectToPage("Users");
        }

        public async Task<IActionResult> OnGetPartial(string msg, int PageNumber = 1, int PageSize = 10, string searchText = "")
        {

           var pagedList1 = await api.GetUsers(User.Identity.GetJWT(), PageNumber, PageSize, searchText);
            return Partial("_UserList",pagedList1);
        }
    }
}

FanBucketUI/Pages/User/Details.cshtml.cs
using FanBucketAPI.Helper;
using FanBucketAPI.ViewModel;
using FanBucketEntity.Model.ENUM;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FanBucketUI.Pages.User
{
    public class DetailsModel : PageModel
    {
        public UserDetailsViewModel usr = new UserDetailsViewModel();
        [BindProperty]
        public ReportActionViewModel ReportActionViewModel { get; set; }
        [BindProperty]
        public CommissionReviewViewModel CommissionReviewViewModel { get; set; }

        private readonly apiRequest api;

        public List<SelectListItem> Actions { get; set; }
        public List<SelectListItem> Days { get; set; }


        public DetailsModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }
        private void Common()
        {
            Actions = EnumHelper.GetEnumValuesAndDescriptions<EnumReportAction>().ToList();
            Days = EnumHelper.GetEnumValuesAndDescriptions<EnumDays>().ToList();
        }
        public async Task<IActionResult> OnGet(Guid Id)
        {
            usr = await api.GetUserDetailsById(Id, User.Identity.GetJWT()); 
            Common();
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await api.UserCommissionReview(CommissionReviewViewModel, User.Identity.GetJWT());
            Common();
            return RedirectToPage("./Details", new { Id = CommissionReviewViewModel.UserId });
        }

        public async Task<IActionResult> OnPostUserReview()
        {
            var user = User.Identity.GetUserId();
            await api.UserReview(ReportActionViewModel, User.Identity.GetJWT());
            return RedirectToPage("./Details", new { Id = ReportActionViewModel.UserId });
        }
    }
}

FanBucketUI/Pages/User/EditProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.User
{
    public class EditProfileModel : PageModel
    {
        public UserDetailsViewModel usr = new UserDetailsViewModel();

        private readonly apiRequest api;
        public EditProfileModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }
        public async Task<IActionResult> OnGet(Guid Id)
        {


            usr = await api.GetUserDetail(User.Identity.GetJWT());
            return Page();
        }

        public async Task<IActionResult> OnPost(EditPersonalViewModel model)
        {


            usr = await api.GetUserDetail(User.Identity.GetJWT());
            return Page();
        }
    }
}

FanBucketUI/Pages/User/ForgotPassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.User
{
    public class ForgotPasswordModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

FanBucketUI/Pages/User/GuestUserPostByImageContent.cshtml.cs
using FanBucketAPI.Models;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace FanBucketUI.Pages.Post
{
    public class GuestUserPostByImageContentModel : PageModel
    {
        //public List<PostMasterCollectionViewModel> postMaster = new List<PostMasterCollectionViewModel>();
        public List<GetUserMediaViewModel> userMedias = new List<GetUserMediaViewModel>();
        private readonly apiRequest api;

        public GuestUserPostByImageContentModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }

        public async Task<IActionResult> OnGet()
        {
            userMedias = await api.GetPostByImageAsGuestUser(User.Identity.GetJWT());

            return Page();
        }
    }
}

FanBucketUI/Pages/User/GuestUserPostByVideoContent.cshtml.cs
using FanBucketAPI.Models;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace FanBucketUI.Pages.Post
{
    public class GuestUserPostByVideoContentModel : PageModel
    {
        public List<PostMasterCollectionViewModel> postMaster = new List<PostMasterCollectionViewModel>();
        private readonly apiRequest api;

        public GuestUserPostByVideoContentModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }

        public async Task<IActionResult> OnGet()
        {
            postMaster = await api.GetUserPostByVideoAsGuestUser(User.Identity.GetJWT());

            return Page();
        }
    }
}

FanBucketUI/Pages/User/LoadWallet.cshtml.cs
using FanBucketAPI.Helper;
using FanBucketAPI.ViewModel;
using FanBucketEntity.Model.ENUM;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FanBucketUI.Pages.User
{
    public class LoadWalletModel : PageModel
    {

        [BindProperty(SupportsGet = true)]
        public decimal amount { get; set; }


        public LoadWalletModel()
        {
            amount = 0;
        }

        public async Task<IActionResult> OnGet(decimal Amount)
        {
            if (amount<=0)
            {
                return RedirectToPage("/Post/Feed");
            }
            amount = Amount;

            return Page();
        }


    }
}

FanBucketUI/Pages/User/Notifications.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.User
{
    public class NotificationsModel : PageModel
    {
        public List<NotificationViewModel> postMaster = new List<NotificationViewModel>();
        private readonly apiRequest api;
        public NotificationsModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }
        public async Task<IActionResult> OnGet()
        {

            postMaster = await api.GetUserNotifications(User.Identity.GetJWT());
            return Page();
        }
    }
}

FanBucketUI/Pages/User/PaymentHistory.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.Procedure;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.User
{
    [Authorize]
    public class PaymentHistoryModel : PageModel
    {
        public List<PaymentHistory> postMaster = new List<PaymentHistory>();
        private readonly apiRequest api;
        public PaymentHistoryModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }
        public async Task<IActionResult> OnGet(Guid NotifyId=default)
        {

            postMaster = await api.GetPaymentHistory(NotifyId,User.Identity.GetJWT());
            return Page();
        }
    }
}

FanBucketUI/Pages/User/PostImages.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketEntity.ViewModel;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.Post
{
    [Authorize]
    public class PostImagesModel : PageModel
    {
        //public List<PostMasterCollectionViewModel> postMaster = new List<PostMasterCollectionViewModel>();
        //public List<GetUserImageContents> postMaster = new List<GetUserImageContents>();
        private readonly apiRequest api;
        public List<GetUserMediaViewModel> userMedias=new List<GetUserMediaViewModel>();

        public PostImagesModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }


        public async Task<IActionResult> OnGet(Guid Id)
        {


            userMedias = await api.GetUserImageContents(Id, User.Identity.GetJWT());

            return Page();
        }
    }
}

FanBucketUI/Pages/User/PostVideo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FanBucketAPI.Models;
using FanBucketUI.API_Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FanBucketUI.Pages.Post
{
    public class PostVideoModel : PageModel
    {
        public List<PostMasterCollectionViewModel> postMaster = new List<PostMasterCollectionViewModel>();
        private readonly apiRequest api;
        public PostVideoModel(apiRequest apiRequest)
        {
            api = apiRequest;
        }

        public async Task<IActionResult> OnGet(Guid Id)
        {

            

            postMaster = await api.GetVideos(Id, User.Identity.GetJWT());

            return Page();
        }

    }
}

FanBucketUI/Pages/Admin/Dashboard.cshtml
@page
@model FanBucketUI.Pages.Admin.DashboardModel
@{
    Layout = "../Shared/_LayoutAdmin.cshtml";
}

<main class="insights--aside dashboard--main">
    <div class="right--aside__wrapper chat--wrapper">
        <section class="dashboard__general">
            <h2 class="section__title">Dashboard</h2>
            <div class="row">
                <div class="col-md-6 col-lg-3">
                    <article class="profile--card ">
                        <div class="card__img bg--sucess">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16.32 14.31"><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M16.2,6.77,12.51.38A.66.66,0,0,0,11.86,0H4.49a.72.72,0,0,0-.7.41C2.59,2.51,1.35,4.65.12,6.77a.66.66,0,0,0,0,.75c1.23,2.12,2.47,4.27,3.69,6.4a.69.69,0,0,0,.68.39H11.8a.76.76,0,0,0,.74-.42c1.08-1.9,2.28-4,3.65-6.33A.69.69,0,0,0,16.2,6.77Zm-1.07.7C14,9.33,13,11.21,11.91,13a.57.57,0,0,1-.56.31H5A.59.59,0,0,1,4.4,13L3,10.56c-.6-1-1.2-2.08-1.79-3.12a.68.68,0,0,1,0-.59C1.8,5.79,2.41,4.73,3,3.68L4.39,1.3A.61.61,0,0,1,5,1C7,1,9,1,11.34,1a.59.59,0,0,1,.58.33l3.2,5.54A.56.56,0,0,1,15.13,7.47Z"></path><path class="cls-1" d="M8.19,3.49h0a3.67,3.67,0,0,0-2.6,6.25,3.61,3.61,0,0,0,2.55,1.08h0a3.71,3.71,0,0,0,2.62-1.07,3.6,3.6,0,0,0,1.07-2.58A3.67,3.67,0,0,0,8.19,3.49ZM9.86,8.85a2.44,2.44,0,0,1-1.72.7h0A2.4,2.4,0,0,1,5.76,7.14a2.34,2.34,0,0,1,.71-1.68,2.31,2.31,0,0,1,1.67-.7h0a2.38,2.38,0,0,1,2.41,2.4A2.42,2.42,0,0,1,9.86,8.85Z"></path></g></g></svg>
                        </div>
                        <div class="card__body">
                            <p class="para small">Total Users</p>
                            <h2 class="card__title">
                                <a asp-page="./Users" target="_blank">
                                    @Model.dashboardViewModel.TotalUsers
                                </a>
                            </h2>
                        </div>
                    </article>
                </div>
                <div class="col-md-6 col-lg-3 ">
                    <article class="profile--card ">

                        <div class="card__img bg">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="13.915" height="12.902" viewBox="0 0 13.915 12.902">
                                <path id="Path_89" data-name="Path 89" d="M-6897.567-5852.808a3.708,3.708,0,0,0-3.708-3.709,3.694,3.694,0,0,0-3.225,1.885,3.694,3.694,0,0,0-3.225-1.885,3.708,3.708,0,0,0-3.709,3.709s-.8,3.064,6.934,9.193C-6896.762-5849.744-6897.567-5852.808-6897.567-5852.808Z" transform="translate(6911.458 5856.517)"></path>
                            </svg>
                        </div>
                        <div class="card__body">
                            <p class="para small">Total Earnings</p>
                            <h2 class="card__title">
                                <a asp-action="#" target="_blank">
                                    @Model.dashboardViewModel.TotalEarnings
                                </a>
                            </h2>
                        </div>
                    </article>
                </div>

                <div class="col-md-6 col-lg-3">
                    <article class="profile--card ">
                        <!--bg--danger
                        -->
                        <div class="card__img bg--prup">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle" viewBox="0 0 16 16">
                                <path d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.146.146 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.163.163 0 0 1-.054.06.116.116 0 0 1-.066.017H1.146a.115.115 0 0 1-.066-.017.163.163 0 0 1-.054-.06.176.176 0 0 1 .002-.183L7.884 2.073a.147.147 0 0 1 .054-.057zm1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566z" />
                                <path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995z" />
                            </svg>
                        </div>
                        <div class="card__body">
                            <p class="para small">Reported Posts</p>
                            <h2 class="card__title">
                                <a asp-page="./ReportedPosts" target="_blank">
                                    @Model.dashboardViewModel.ReportedPostsTotal
                                </a>
                            </h2>
                        </div>
                    </article>
                </div>

                <div class="col-md-6 col-lg-3 ">
                    <article class="profile--card ">
                        <!-- bg--danger -->
                        <div class="card__img  bg--blue">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                                <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                            </svg>
                        </div>
                        <div class="card__body">
                            <p class="para small">New Members</p>
                            <h2 class="card__title">
                                <a asp-page="./NewUsers" target="_blank">
                                    @Model.dashboardViewModel.NewUsers.Count
                                </a>
                            </h2>
                        </div>
                    </article>
                </div>
            </div>
        </section>

        <section class="chat--wrapper__body">
            <div class="row">
                <div class="col-md-12">
                    <article class="card chart--card card__margin">
                        <div class="card__top title--wrapper">
                            <h2 class="section__title">Monthly Recap Report</h2>
                        </div>
                        <div class="card__body">
                            <div class="card__body__left">
                                <h2 class="section__title__lg text--prup mb-0">$58.00</h2>
                                <p class="para">Total Earnings<span class="text--danger"><i class="bi bi-arrow-down"></i> 13.3%</span> vs prev 2 days </p>



                                <div id="locked--post--svg" class="chart__wrapper">
                                    <div class=" loading">
                                        <div class="d-flex form-upolading loader__wrapper">
                                            <div class="loader">
                                                <div class="box">
                                                    <img src="~/Content/gallery/logoWhite.png" alt="fanbucket">
                                                </div>
                                                <div class="shadow"></div>
                                            </div>
                                            <h2 class="section__title">Loading ...</h2>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>

                <div class="col-md-12">
                    <article class="card chart--card card__margin">
                        <div class="card__top title--wrapper">
                            <h2 class="section__title">Visitors Report</h2>
                        </div>
                        <div class="card__body">
                            <div class="card__body__left">
                                <h2 class="section__title__lg text--prup mb-0">$58.00</h2>
                                <p class="para">Total Earnings<span class="text--danger"><i class="bi bi-arrow-down"></i> 13.3%</span> vs prev 2 days </p>



                                <div id="geoLocation--svg" class="chart__wrapper">
                                    <div class="loading">
                                        <div class="d-flex form-upolading loader__wrapper">
                                            <div class="loader">
                                                <div class="box">
                                                    <img src="~/Content/gallery/logoWhite.png" alt="fanbucket">
                                                </div>
                                                <div class="shadow"></div>
                                            </div>
                                            <h2 class="section__title">Loading ...</h2>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
        </section>
    </div>
</main>

FanBucketUI/Pages/Admin/_UserList.cshtml
@model FanBucketEntity.Wrappers.PagedResponse<List<FanBucketEntity.ViewModel.UserDetailsViewModel>>

<div class="post-list">

    @foreach (var item in Model.Data)
    {


            <a href="/User/Details?Id=@item.Id" class=" list-group-item-action " aria-current="true">
                <div class="profile--card">
                    <div class="card__img active">
                        <img src="@item.ProfileImgLocation" alt="">
                    </div>
                    <div class="card__body">
                        <h2 class="card__title">@item.Fullname (@item.Username)</h2>
                        <p class="para small">@item.Email</p>

                    </div>
                    @if (!item.Badges.Any(x => x.Name == "Verified"))
                    {
                        <form asp-page-handler="Verify" class="ml-auto" method="post">
                            <input type="hidden" name="UserId" value="@item.Id" />
                            <input type="submit" class="dashboard--common--btn" value="Verify" />
                        </form>
                    }
                </div>

            </a>

    }

</div>

<!-- Display pagination links -->
<div class="pagination">
    Total Records: @Model.TotalRecords | &nbsp;
    @if (Model.PreviousPage != null)
    {
        <a href="javascript:void(0);" onclick="searchFilter(@Model.PreviousPageNumber)">Previous Page  </a> @Html.Raw("&nbsp;");

    }
    @if (Model.NextPage != null)
    {
        <a href="javascript:void(0);" onclick="searchFilter(@Model.NextPageNumber)"> Next Page</a> @Html.Raw("&nbsp;");

    }

</div>